# Generated by Django 4.0 on 2022-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='image',
            field=models.ImageField(default=123, upload_to=''),
            preserve_default=False,
        ),
    ]
