# Generated by Django 4.0 on 2022-04-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seamstress',
            options={'verbose_name': 'Seamstress', 'verbose_name_plural': 'Seamstresses'},
        ),
    ]
